export const APP = {
  previewLoading: 'Preparing preview…',
  preferencesLoadFailedMessage: 'Snipworth could not load saved preferences.',
  preferencesSaveFailedMessage: 'Snipworth could not save your preferences.',
  tabCodeLabel: 'Code',
  tabPreviewLabel: 'Preview',
  tabConfigLabel: 'Config',
  brandPrefix: 'Snip',
  brandSuffix: 'worth',
  logoLabel: 'Snipworth logo',
  supportButton: 'Support',
  supportTooltip: 'Buy me a coffee',
  githubTooltip: 'Open GitHub repository',
  openFullTabTooltip: 'Open in full tab',
  openFullTabFailedMessage: 'Snipworth could not open the full-tab editor.',
} as const;
